# coding: utf-8

"""
    PowerManifest API

    API for PowerManifest backend

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class JournalStats(BaseModel):
    """
    JournalStats
    """  # noqa: E501
    totalEntries: Optional[StrictInt] = Field(default=None, description="Total number of entries", alias="totalEntries")
    streakDays: Optional[StrictInt] = Field(default=None, description="Current streak in days", alias="streakDays")
    mostCommonMoods: Optional[List[Dict[str, Any]]] = Field(default=None, description="Most common moods with counts", alias="mostCommonMoods")
    topThemes: Optional[List[Dict[str, Any]]] = Field(default=None, description="Top themes with counts", alias="topThemes")
    growthIndicators: Optional[Dict[str, Any]] = Field(default=None, description="Growth indicators", alias="growthIndicators")
    __properties: ClassVar[List[str]] = ["totalEntries", "streakDays", "mostCommonMoods", "topThemes", "growthIndicators"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JournalStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if totalEntries (nullable) is None
        # and model_fields_set contains the field
        if self.totalEntries is None and "totalEntries" in self.model_fields_set:
            _dict['totalEntries'] = None

        # set to None if streakDays (nullable) is None
        # and model_fields_set contains the field
        if self.streakDays is None and "streakDays" in self.model_fields_set:
            _dict['streakDays'] = None

        # set to None if mostCommonMoods (nullable) is None
        # and model_fields_set contains the field
        if self.mostCommonMoods is None and "mostCommonMoods" in self.model_fields_set:
            _dict['mostCommonMoods'] = None

        # set to None if topThemes (nullable) is None
        # and model_fields_set contains the field
        if self.topThemes is None and "topThemes" in self.model_fields_set:
            _dict['topThemes'] = None

        # set to None if growthIndicators (nullable) is None
        # and model_fields_set contains the field
        if self.growthIndicators is None and "growthIndicators" in self.model_fields_set:
            _dict['growthIndicators'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JournalStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "totalEntries": obj.get("totalEntries"),
            "streakDays": obj.get("streakDays"),
            "mostCommonMoods": obj.get("mostCommonMoods"),
            "topThemes": obj.get("topThemes"),
            "growthIndicators": obj.get("growthIndicators")
        })
        return _obj