# coding: utf-8

"""
    PowerManifest API

    API for PowerManifest backend

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class JournalPatterns(BaseModel):
    """
    JournalPatterns
    """  # noqa: E501
    recurringThemes: Optional[List[Dict[str, Any]]] = Field(default=None, description="Recurring themes analysis", alias="recurringThemes")
    emotionalPatterns: Optional[List[Dict[str, Any]]] = Field(default=None, description="Emotional patterns analysis", alias="emotionalPatterns")
    breakthroughMoments: Optional[List[Dict[str, Any]]] = Field(default=None, description="Breakthrough moments", alias="breakthroughMoments")
    __properties: ClassVar[List[str]] = ["recurringThemes", "emotionalPatterns", "breakthroughMoments"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JournalPatterns from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if recurringThemes (nullable) is None
        # and model_fields_set contains the field
        if self.recurringThemes is None and "recurringThemes" in self.model_fields_set:
            _dict['recurringThemes'] = None

        # set to None if emotionalPatterns (nullable) is None
        # and model_fields_set contains the field
        if self.emotionalPatterns is None and "emotionalPatterns" in self.model_fields_set:
            _dict['emotionalPatterns'] = None

        # set to None if breakthroughMoments (nullable) is None
        # and model_fields_set contains the field
        if self.breakthroughMoments is None and "breakthroughMoments" in self.model_fields_set:
            _dict['breakthroughMoments'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JournalPatterns from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "recurringThemes": obj.get("recurringThemes"),
            "emotionalPatterns": obj.get("emotionalPatterns"),
            "breakthroughMoments": obj.get("breakthroughMoments")
        })
        return _obj