# coding: utf-8

"""
    PowerManifest API

    API for PowerManifest backend

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ProcessEntryResponse(BaseModel):
    """
    ProcessEntryResponse
    """  # noqa: E501
    insights: Optional[Dict[str, Any]] = Field(default=None, description="AI processing insights")
    __properties: ClassVar[List[str]] = ["insights"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProcessEntryResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if insights (nullable) is None
        # and model_fields_set contains the field
        if self.insights is None and "insights" in self.model_fields_set:
            _dict['insights'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProcessEntryResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # Create insights object structure from OpenAPI spec
        insights = None
        if obj.get("insights"):
            insights = {
                "tags": obj["insights"].get("tags", []),
                "emotionalState": obj["insights"].get("emotionalState"),
                "themes": obj["insights"].get("themes", []),
                "suggestedActions": obj["insights"].get("suggestedActions", [])
            }

        _obj = cls.model_validate({
            "insights": insights
        })
        return _obj